[workspace]
resolver = "2"
members = ["declavatar2", "da2"]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["KOBAYASHI Yū <kb10uy@kb10uy.org>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/kb10uy/declavatar2"

[workspace.dependencies]
