[package]
name = "da2"
version.workspace = true
description.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true

[lib]
crate-type = ["cdylib"]

[features]
bindings = ["dep:cbindgen"]

[dependencies]
declavatar2 = { workspace = true }

[build-dependencies]
cbindgen = { workspace = true, optional = true }

[dev-dependencies]
rstest = { workspace = true }
