use crate::{
    core::{
        phase::Phase,
        value_set::{MaybeZeroableEntry, ValueSet},
    },
    unity::{AnimatedTarget, AnimatedValue},
};

#[derive(Debug, Clone)]
pub struct FixedAnimationEntry<Ph: Phase> {
    pub key: AnimatedTarget<Ph>,
    pub value: AnimatedValue<Ph::ObjectRef>,
}

impl<Ph: Phase> MaybeZeroableEntry for FixedAnimationEntry<Ph> {
    type Key = AnimatedTarget<Ph>;

    fn key(&self) -> Self::Key {
        self.key.clone()
    }

    fn zeroed(&self) -> Option<Self> {
        self.value.zeroed().map(|value| Self { key: self.key.clone(), value })
    }
}

/// Represents an AnimationClip generated by declavatar2.
#[derive(Debug, Clone)]
pub enum InlineAnimation<Ph: Phase> {
    Fixed(ValueSet<FixedAnimationEntry<Ph>>),
    Keyed,
}
