use thiserror::Error;

use crate::{
    core::{
        phase::Phase,
        value_set::{MaybeZeroableEntry, ValueSet},
    },
    unity::{AnimatedTarget, AnimatedValue, AnimatedValueType},
};

/// Represents an AnimationClip generated by declavatar2.
#[derive(Debug, Clone, PartialEq)]
pub enum InlineAnimation<Ph: Phase> {
    /// Single-frame clip that sets every target to a fixed value.
    Fixed(ValueSet<FixedAnimationEntry<Ph>>),

    /// Clip with per-target curves over normalized time.
    Keyed(KeyedAnimation<Ph>),
}

#[derive(Debug, Clone, PartialEq)]
pub struct FixedAnimationEntry<Ph: Phase> {
    pub key: AnimatedTarget<Ph>,
    pub value: AnimatedValue<Ph::ObjectRef>,
}

impl<Ph: Phase> MaybeZeroableEntry for FixedAnimationEntry<Ph> {
    type Key = AnimatedTarget<Ph>;

    fn key(&self) -> Self::Key {
        self.key.clone()
    }

    fn zeroed(&self) -> Option<Self> {
        self.value.zeroed().map(|value| Self { key: self.key.clone(), value })
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct KeyedAnimation<Ph: Phase> {
    pub attributes: ClipAttributes,
    pub curves: ValueSet<KeyedAnimationEntry<Ph>>,
}

impl<Ph: Phase> Default for KeyedAnimation<Ph> {
    fn default() -> Self {
        Self {
            attributes: ClipAttributes::default(),
            curves: ValueSet::new(),
        }
    }
}

/// Clip-level settings that affect runtime playback.
/// `length` is in seconds; normalized time `1.0` of every curve maps to it.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct ClipAttributes {
    pub length: f64,
    pub loop_time: bool,
    pub loop_blend: bool,
    pub cycle_offset: f64,
}

impl Default for ClipAttributes {
    fn default() -> Self {
        Self {
            length: 1.0,
            loop_time: false,
            loop_blend: false,
            cycle_offset: 0.0,
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct KeyedAnimationEntry<Ph: Phase> {
    pub key: AnimatedTarget<Ph>,
    pub curve: Curve<Ph::ObjectRef>,
}

impl<Ph: Phase> MaybeZeroableEntry for KeyedAnimationEntry<Ph> {
    type Key = AnimatedTarget<Ph>;

    fn key(&self) -> Self::Key {
        self.key.clone()
    }

    fn zeroed(&self) -> Option<Self> {
        self.curve.first.value.zeroed().map(|value| Self {
            key: self.key.clone(),
            curve: Curve::single(Keyframe { time: 0.0, value }),
        })
    }
}

impl<Ph: Phase> From<FixedAnimationEntry<Ph>> for KeyedAnimationEntry<Ph> {
    fn from(entry: FixedAnimationEntry<Ph>) -> Self {
        Self {
            key: entry.key,
            curve: Curve::single(Keyframe { time: 0.0, value: entry.value }),
        }
    }
}

/// Non-empty sequence of keyframes with an interpolation for each segment between them.
#[derive(Debug, Clone, PartialEq)]
pub struct Curve<R> {
    pub first: Keyframe<R>,
    pub rest: Vec<(Interpolation, Keyframe<R>)>,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Keyframe<R> {
    /// Normalized time in `[0.0, 1.0]`.
    pub time: f64,
    pub value: AnimatedValue<R>,
}

/// How a segment progresses from its starting keyframe to the next one.
/// `Bezier` follows the CSS `cubic-bezier(x1, y1, x2, y2)` convention over the segment.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Interpolation {
    Constant,
    Linear,
    Bezier { x1: f64, y1: f64, x2: f64, y2: f64 },
}

#[derive(Debug, Clone, Copy, PartialEq, Error)]
pub enum CurveError {
    #[error("keyframe time {0} is out of range [0.0, 1.0]")]
    TimeOutOfRange(f64),

    #[error("keyframe time {next} does not increase from previous {previous}")]
    TimeNotIncreasing { previous: f64, next: f64 },

    #[error("expected {expected:?} value but found {found:?}")]
    InconsistentValueType { expected: AnimatedValueType, found: AnimatedValueType },

    #[error("{interpolation:?} interpolation cannot be applied to {value_type:?} values")]
    InterpolationNotApplicable {
        interpolation: Interpolation,
        value_type: AnimatedValueType,
    },

    #[error("bezier control point x {0} is out of range [0.0, 1.0]")]
    ControlPointOutOfRange(f64),
}

impl Interpolation {
    pub fn is_applicable_to(&self, value_type: AnimatedValueType) -> bool {
        match self {
            Interpolation::Constant => true,
            Interpolation::Linear | Interpolation::Bezier { .. } => value_type.is_interpolable(),
        }
    }

    pub fn validate(&self) -> Result<(), CurveError> {
        if let Interpolation::Bezier { x1, x2, .. } = self {
            for x in [*x1, *x2] {
                if !(0.0..=1.0).contains(&x) {
                    return Err(CurveError::ControlPointOutOfRange(x));
                }
            }
        }
        Ok(())
    }
}

impl<R> Curve<R> {
    pub fn single(keyframe: Keyframe<R>) -> Self {
        Self {
            first: keyframe,
            rest: Vec::new(),
        }
    }

    pub fn keyframe_count(&self) -> usize {
        self.rest.len() + 1
    }

    pub fn keyframes(&self) -> impl Iterator<Item = &Keyframe<R>> {
        std::iter::once(&self.first).chain(self.rest.iter().map(|(_, k)| k))
    }

    pub fn segments(&self) -> impl Iterator<Item = (&Keyframe<R>, Interpolation, &Keyframe<R>)> {
        self.keyframes().zip(&self.rest).map(|(from, (interpolation, to))| (from, *interpolation, to))
    }

    pub fn last(&self) -> &Keyframe<R> {
        self.rest.last().map(|(_, k)| k).unwrap_or(&self.first)
    }
}

impl<R: Clone> Curve<R> {
    pub fn value_type(&self) -> AnimatedValueType {
        self.first.value.value_type()
    }

    pub fn validate(&self) -> Result<(), CurveError> {
        let value_type = self.value_type();
        for keyframe in self.keyframes() {
            if !(0.0..=1.0).contains(&keyframe.time) {
                return Err(CurveError::TimeOutOfRange(keyframe.time));
            }
            let found = keyframe.value.value_type();
            if found != value_type {
                return Err(CurveError::InconsistentValueType { expected: value_type, found });
            }
        }
        for (from, interpolation, to) in self.segments() {
            if to.time <= from.time {
                return Err(CurveError::TimeNotIncreasing {
                    previous: from.time,
                    next: to.time,
                });
            }
            interpolation.validate()?;
            if !interpolation.is_applicable_to(value_type) {
                return Err(CurveError::InterpolationNotApplicable { interpolation, value_type });
            }
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use rstest::*;

    use super::*;
    use crate::unity::{AnimatedGameObjectProperty, AnimatedGameObjectTarget, AnimatedRendererProperty, AnimatedRendererTarget};

    #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
    enum TestPhase {}

    impl Phase for TestPhase {
        type ParameterRef = &'static str;
        type ObjectPath = &'static str;
        type ComponentType = &'static str;
        type ObjectRef = &'static str;
    }

    fn blend_shape(name: &str) -> AnimatedTarget<TestPhase> {
        AnimatedTarget::Renderer(AnimatedRendererTarget {
            path: "Body",
            renderer_type: "UnityEngine.SkinnedMeshRenderer".into(),
            property: AnimatedRendererProperty::BlendShape { name: name.into() },
        })
    }

    fn active(path: &'static str) -> AnimatedTarget<TestPhase> {
        AnimatedTarget::GameObject(AnimatedGameObjectTarget {
            path,
            property: AnimatedGameObjectProperty::Active,
        })
    }

    fn material_slot(path: &'static str) -> AnimatedTarget<TestPhase> {
        AnimatedTarget::Renderer(AnimatedRendererTarget {
            path,
            renderer_type: "UnityEngine.MeshRenderer".into(),
            property: AnimatedRendererProperty::Serialized {
                name: "m_Materials.Array.data[0]".into(),
            },
        })
    }

    fn key(time: f64, value: f64) -> Keyframe<&'static str> {
        Keyframe {
            time,
            value: AnimatedValue::Float(value),
        }
    }

    fn curve(first: Keyframe<&'static str>, rest: impl IntoIterator<Item = (Interpolation, Keyframe<&'static str>)>) -> Curve<&'static str> {
        Curve {
            first,
            rest: rest.into_iter().collect(),
        }
    }

    #[rstest]
    fn fixed_entry_becomes_single_keyframe_curve() {
        let fixed = FixedAnimationEntry {
            key: blend_shape("Smile"),
            value: AnimatedValue::Float(100.0),
        };
        let keyed: KeyedAnimationEntry<TestPhase> = fixed.into();
        assert_eq!(keyed.key, blend_shape("Smile"));
        assert_eq!(keyed.curve, Curve::single(key(0.0, 100.0)));
        assert_eq!(keyed.curve.keyframe_count(), 1);
        assert_eq!(keyed.curve.segments().count(), 0);
    }

    #[rstest]
    fn keyed_entry_zeroes_to_single_zero_keyframe() {
        let entry = KeyedAnimationEntry {
            key: blend_shape("Smile"),
            curve: curve(key(0.0, 30.0), [(Interpolation::Linear, key(1.0, 100.0))]),
        };
        let zeroed = entry.zeroed().unwrap();
        assert_eq!(zeroed.key, blend_shape("Smile"));
        assert_eq!(zeroed.curve, Curve::single(key(0.0, 0.0)));

        let reference = KeyedAnimationEntry {
            key: material_slot("Body"),
            curve: Curve::single(Keyframe {
                time: 0.0,
                value: AnimatedValue::ObjectReference("Materials/Skin.mat"),
            }),
        };
        assert!(reference.zeroed().is_none());
    }

    #[rstest]
    fn keyed_curves_fill_missing_targets_with_zero() {
        let mut defaults: ValueSet<KeyedAnimationEntry<TestPhase>> = ValueSet::from([KeyedAnimationEntry {
            key: blend_shape("Smile"),
            curve: Curve::single(key(0.0, 0.0)),
        }]);
        let other = ValueSet::from([KeyedAnimationEntry {
            key: blend_shape("Angry"),
            curve: curve(key(0.0, 0.0), [(Interpolation::Linear, key(1.0, 100.0))]),
        }]);

        assert!(defaults.union_fill_as_zero(std::slice::from_ref(&other)).is_ok());
        let keys: Vec<_> = defaults.entries().map(|(k, _)| k.clone()).collect();
        assert_eq!(keys, vec![blend_shape("Angry"), blend_shape("Smile")]);
    }

    #[rstest]
    fn segments_pair_consecutive_keyframes() {
        let curve = curve(
            key(0.0, 0.0),
            [(Interpolation::Linear, key(0.5, 50.0)), (Interpolation::Constant, key(1.0, 100.0))],
        );
        let segments: Vec<_> = curve.segments().map(|(from, i, to)| (from.time, i, to.time)).collect();
        assert_eq!(segments, vec![(0.0, Interpolation::Linear, 0.5), (0.5, Interpolation::Constant, 1.0)]);
        assert_eq!(curve.last().time, 1.0);
        assert_eq!(curve.keyframes().count(), 3);
    }

    #[rstest]
    #[case::single(Curve::single(key(0.0, 1.0)))]
    #[case::linear(curve(key(0.0, 0.0), [(Interpolation::Linear, key(1.0, 100.0))]))]
    #[case::bezier(curve(key(0.0, 0.0), [(Interpolation::Bezier { x1: 0.42, y1: 0.0, x2: 0.58, y2: 1.0 }, key(1.0, 100.0))]))]
    #[case::overshoot(curve(key(0.0, 0.0), [(Interpolation::Bezier { x1: 0.3, y1: -0.5, x2: 0.7, y2: 1.5 }, key(1.0, 100.0))]))]
    #[case::three_keys(curve(key(0.0, 0.0), [(Interpolation::Linear, key(0.25, 10.0)), (Interpolation::Constant, key(1.0, 100.0))]))]
    fn valid_curves_pass(#[case] curve: Curve<&'static str>) {
        assert_eq!(curve.validate(), Ok(()));
    }

    #[rstest]
    #[case::negative_time(Curve::single(key(-0.1, 0.0)), CurveError::TimeOutOfRange(-0.1))]
    #[case::over_time(curve(key(0.0, 0.0), [(Interpolation::Linear, key(1.5, 1.0))]), CurveError::TimeOutOfRange(1.5))]
    #[case::same_time(
        curve(key(0.5, 0.0), [(Interpolation::Linear, key(0.5, 1.0))]),
        CurveError::TimeNotIncreasing { previous: 0.5, next: 0.5 },
    )]
    #[case::backwards(
        curve(key(0.0, 0.0), [(Interpolation::Linear, key(1.0, 1.0)), (Interpolation::Linear, key(0.5, 1.0))]),
        CurveError::TimeNotIncreasing { previous: 1.0, next: 0.5 },
    )]
    #[case::control_point(
        curve(key(0.0, 0.0), [(Interpolation::Bezier { x1: 1.2, y1: 0.0, x2: 0.5, y2: 1.0 }, key(1.0, 1.0))]),
        CurveError::ControlPointOutOfRange(1.2),
    )]
    fn invalid_curves_fail(#[case] curve: Curve<&'static str>, #[case] expected: CurveError) {
        assert_eq!(curve.validate(), Err(expected));
    }

    #[rstest]
    #[case(CurveError::TimeOutOfRange(1.5), "keyframe time 1.5 is out of range [0.0, 1.0]")]
    #[case(CurveError::TimeNotIncreasing { previous: 1.0, next: 0.5 }, "keyframe time 0.5 does not increase from previous 1")]
    #[case(
        CurveError::InterpolationNotApplicable { interpolation: Interpolation::Linear, value_type: AnimatedValueType::Bool },
        "Linear interpolation cannot be applied to Bool values",
    )]
    fn curve_errors_display_messages(#[case] error: CurveError, #[case] expected: &str) {
        assert_eq!(error.to_string(), expected);
    }

    #[rstest]
    fn mixed_value_types_fail() {
        let curve = curve(
            key(0.0, 0.0),
            [(
                Interpolation::Constant,
                Keyframe {
                    time: 1.0,
                    value: AnimatedValue::Int(1),
                },
            )],
        );
        assert_eq!(
            curve.validate(),
            Err(CurveError::InconsistentValueType {
                expected: AnimatedValueType::Float,
                found: AnimatedValueType::Int,
            })
        );
    }

    #[rstest]
    #[case::bool_linear(AnimatedValue::Bool(false), AnimatedValue::Bool(true), Interpolation::Linear)]
    #[case::int_bezier(AnimatedValue::Int(0), AnimatedValue::Int(3), Interpolation::Bezier { x1: 0.0, y1: 0.0, x2: 1.0, y2: 1.0 })]
    #[case::reference_linear(AnimatedValue::ObjectReference("A.mat"), AnimatedValue::ObjectReference("B.mat"), Interpolation::Linear)]
    fn non_interpolable_values_require_constant(
        #[case] from: AnimatedValue<&'static str>,
        #[case] to: AnimatedValue<&'static str>,
        #[case] interpolation: Interpolation,
    ) {
        let value_type = from.value_type();
        let curve = Curve {
            first: Keyframe {
                time: 0.0,
                value: from.clone(),
            },
            rest: vec![(interpolation, Keyframe { time: 1.0, value: to.clone() })],
        };
        assert_eq!(curve.validate(), Err(CurveError::InterpolationNotApplicable { interpolation, value_type }));

        let stepped = Curve {
            first: Keyframe { time: 0.0, value: from },
            rest: vec![(Interpolation::Constant, Keyframe { time: 1.0, value: to })],
        };
        assert_eq!(stepped.validate(), Ok(()));
    }

    #[rstest]
    fn active_target_accepts_stepped_bool_curve() {
        let entry = KeyedAnimationEntry {
            key: active("Armature/Hat"),
            curve: Curve {
                first: Keyframe {
                    time: 0.0,
                    value: AnimatedValue::Bool(false),
                },
                rest: vec![(
                    Interpolation::Constant,
                    Keyframe {
                        time: 0.5,
                        value: AnimatedValue::Bool(true),
                    },
                )],
            },
        };
        assert_eq!(entry.curve.validate(), Ok(()));
        assert_eq!(entry.zeroed().unwrap().curve.first.value, AnimatedValue::Bool(false));
    }

    #[rstest]
    fn clip_attributes_default_to_one_second_non_looping() {
        let attributes = ClipAttributes::default();
        assert_eq!(attributes.length, 1.0);
        assert!(!attributes.loop_time);
        assert!(!attributes.loop_blend);
        assert_eq!(attributes.cycle_offset, 0.0);
        assert_eq!(KeyedAnimation::<TestPhase>::default().curves.entries().count(), 0);
    }
}
