[package]
name = "declavatar2"
description = "Avatar Asset Composition System, Version 2"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
